version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sca_mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Your_password123", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mssql-data:/var/opt/mssql

  backend:
    build: ./server
    container_name: sca_backend
    environment:
      - DB_HOST=mssql
      - DB_NAME=master
      - DB_USER=sa
      - DB_PASS=Your_password123
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      mssql:
        condition: service_healthy

volumes:
  mssql-data:
